<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QRJIP05" failures="0" tests="7" name="sctevt_runner_Execution.sctevtExceution" time="48.749" errors="1" timestamp="2025-06-24T16:01:00 IST" skipped="1">
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="afterSuite" time="0.334">
    <error message="Cannot invoke &quot;String.replace(java.lang.CharSequence, java.lang.CharSequence)&quot; because the return value of &quot;java.util.Properties.getProperty(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "java.util.Properties.getProperty(String)" is null
at sctevt_runner_Execution.sctevtExceution.afterSuite(sctevtExceution.java:371)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- afterSuite -->
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT" time="5.839"/>
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT" time="12.955"/>
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT" time="5.889"/>
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT" time="17.914"/>
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT" time="5.818"/>
  <system-out/>
  <testcase classname="sctevt_runner_Execution.sctevtExceution" name="ScTEandVT2">
    <skipped/>
  </testcase> <!-- ScTEandVT2 -->
  <system-out/>
</testsuite> <!-- sctevt_runner_Execution.sctevtExceution -->
